---
- name: Configuración inicial y despliegue de software en servidores
  hosts: all
  become: yes

  tasks:
    - name: Actualizar la cache de apt
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Instalar Cowsay
      apt:
        name: cowsay
        state: present

    - name: Crear un archivo de prueba
      copy:
        content: "Este es un archivo de prueba creado por Ansible.\n"
        dest: /tmp/archivo_prueba.txt

    - name: Copiar archivos desde el controlador a los servidores
      copy:
        src: /path/to/your/local/file.txt
        dest: /home/vagrant/file.txt

    - name: Crear carpetas en el servidor
      file:
        path: /home/vagrant/nueva_carpeta
        state: directory
        mode: '0755'

    - name: Iniciar el servicio Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Agregar un usuario al servidor
      user:
        name: nuevo_usuario
        comment: "Un usuario añadido por Ansible"
        shell: /bin/bash
        groups: sudo
        state: present
        createhome: yes

    - name: Ejecutar un script en el servidor
      script:
        cmd: /path/to/your/script.sh
